"use client";
import { X } from "lucide-react";
import { FormEvent, useState } from "react";
import type { Instrument, TradeWithAnalysis } from "@/types";
import { Button } from "@/components/ui/button";
import { strategyOptions } from "@/lib/display-labels";

export function TradeForm({ instrument, defaultDate, defaultPrice, trade, onClose, onSaved }: { instrument: Instrument; defaultDate: string; defaultPrice: number; trade?: TradeWithAnalysis | null; onClose: () => void; onSaved: (trade: TradeWithAnalysis) => void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [side, setSide] = useState(trade?.side ?? "BUY"); const isEdit = Boolean(trade);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const values = Object.fromEntries(new FormData(event.currentTarget)); const body = { ...values, instrumentId: instrument.id, accountId: Number(values.accountId || 1), price: String(values.price), quantity: String(values.quantity), fee: String(values.fee || 0), estimatedExitFee: String(values.estimatedExitFee || 0), tradeAt: `${values.tradeDate}T${values.tradeTime}:00`, tags: String(values.tags ?? "").split(",").map((item) => item.trim()).filter(Boolean) };
    try { const response = await fetch(isEdit ? `/api/trades/${trade!.id}` : "/api/trades", { method: isEdit ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); if (!response.ok) throw new Error(json.message ?? "无法保存交易。"); onSaved(json.trade); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法保存交易。"); } finally { setSaving(false); }
  }
  const time = trade?.tradeAt.match(/T(\d{2}:\d{2})/)?.[1] ?? "10:30";
  return <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="dialog" role="dialog" aria-modal="true" aria-label="记录交易"><form onSubmit={submit}><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-base font-semibold">{isEdit ? "编辑交易" : "记录交易"}</h2><p className="mt-1 text-xs text-muted">{instrument.name} · {instrument.symbol}</p></div><Button type="button" variant="ghost" onClick={onClose} className="h-8 w-8 p-0" aria-label="关闭"><X size={16} /></Button></div><div className="grid gap-4 p-5 sm:grid-cols-2">
    <label><span className="label">方向</span><select name="side" className="field" value={side} onChange={(event) => setSide(event.target.value as "BUY" | "SELL")}><option value="BUY">买入</option><option value="SELL">卖出</option></select></label><label><span className="label">策略</span><select name="strategy" className="field" defaultValue={trade?.strategy ?? "Manual"}>{strategyOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
    <label><span className="label">账户编号</span><input name="accountId" type="number" min="1" step="1" required className="field" defaultValue={trade?.accountId ?? 1} /><span className="mt-1.5 block text-[10px] leading-4 text-muted">不同券商账户使用不同编号，持仓成本不会跨账户合并。</span></label><div className="hidden sm:block" />
    <label><span className="label">交易日期</span><input name="tradeDate" type="date" required className="field" defaultValue={trade?.tradeDate ?? defaultDate} /></label><label><span className="label">交易时间</span><input name="tradeTime" type="time" required className="field" defaultValue={time} /></label>
    <label><span className="label">成交价格（{instrument.currency}）</span><input name="price" type="number" step="0.0001" min="0.0001" required className="field" defaultValue={trade?.price ?? defaultPrice.toFixed(2)} /></label><label><span className="label">数量</span><input name="quantity" type="number" step="0.0001" min="0.0001" required className="field" defaultValue={trade?.quantity ?? "100"} /></label>
    <label><span className="label">{side === "BUY" ? "买入手续费" : "卖出手续费"}（{instrument.currency}，总额）</span><input name="fee" type="number" step="0.01" min="0" className="field" defaultValue={trade?.fee ?? "0"} /></label>{side === "BUY" ? <label><span className="label">预计当前持仓全部卖出费用</span><input name="estimatedExitFee" type="number" step="0.01" min="0" className="field" defaultValue={trade?.estimatedExitFee ?? trade?.fee ?? "0"} /><span className="mt-1.5 block text-[10px] leading-4 text-muted">股票配置已设置手续费模型时会动态计算；否则把这里视为交易后整个持仓一次平仓的估算总额。</span></label> : <input type="hidden" name="estimatedExitFee" value="0" />}
    <label className="sm:col-span-2"><span className="label">标签 <span className="font-normal">· 使用逗号分隔</span></span><input name="tags" className="field" defaultValue={trade?.tags?.join(", ") ?? ""} placeholder="突破, 按计划" /></label>
    <label className="sm:col-span-2"><span className="label">交易理由</span><textarea name="reason" rows={2} className="field resize-y" defaultValue={trade?.reason ?? ""} placeholder="当时你观察到了什么？" /></label><label className="sm:col-span-2"><span className="label">交易计划</span><textarea name="plan" rows={2} className="field resize-y" defaultValue={trade?.plan ?? ""} placeholder="失效条件、目标位和持仓管理计划。" /></label>
    <label><span className="label">计划止损</span><input name="plannedStop" type="number" step="0.0001" className="field" defaultValue={trade?.plannedStop ?? ""} /></label><label><span className="label">计划目标</span><input name="plannedTarget" type="number" step="0.0001" className="field" defaultValue={trade?.plannedTarget ?? ""} /></label>
    <label className="sm:col-span-2"><span className="label">备注</span><textarea name="note" rows={2} className="field resize-y" defaultValue={trade?.note ?? ""} /></label>{error ? <div className="sm:col-span-2 rounded-md bg-sell/10 p-3 text-xs text-sell">{error}</div> : null}
  </div><div className="flex justify-end gap-2 border-t border-line px-5 py-4"><Button type="button" onClick={onClose}>取消</Button><Button type="submit" variant="primary" disabled={saving}>{saving ? "正在保存…" : isEdit ? "保存修改" : "记录交易"}</Button></div></form></div></div>;
}
